class ProductModel {
  final String imgUrl;
  final String title;
  final String weight;
  final String originalPrice;
  final String discountedPrice;
  final String offPercentage;
  final bool inCartFlag;
  final int inCartQuantity;
  final int id;
  final String currency;

  const ProductModel({
    this.currency = '',
    this.id = 0,
    this.discountedPrice = '',
    this.imgUrl = '',
    this.offPercentage = '',
    this.originalPrice = '',
    this.title = '',
    this.weight = '',
    this.inCartFlag = false,
    this.inCartQuantity = 0,
  });

  static List<ProductModel> productListFreshVeggies = [
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/mangoes.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/apples.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/jamun.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/raspberries.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/strawberries.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/raspberries.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/mangoes.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/apples.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/jamun.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/raspberries.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/strawberries.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/raspberries.png',
      title: 'Yello Mango Alphonso Fresh',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    )
  ];
  static List<ProductModel> productListCreamfillsBiscuits = [
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/horlicks.png',
      title: 'Horlicks Biscuits',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/butter.png',
      title: '20 - 20 Butter Jeera Cookies',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/hideandseek.png',
      title: 'Hide & Seek Chocolate Chip',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/horlicks.png',
      title: 'Horlicks Biscuits',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/butter.png',
      title: '20 - 20 Butter Jeera Cookies',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/hideandseek.png',
      title: 'Hide & Seek Chocolate Chip',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/horlicks.png',
      title: 'Horlicks Biscuits',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/butter.png',
      title: '20 - 20 Butter Jeera Cookies',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/hideandseek.png',
      title: 'Hide & Seek Chocolate Chip',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/horlicks.png',
      title: 'Horlicks Biscuits',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/butter.png',
      title: '20 - 20 Butter Jeera Cookies',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/hideandseek.png',
      title: 'Hide & Seek Chocolate Chip',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
  ];

  static List<ProductModel> productListCookiesBiscuits = [
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/horlicks.png',
      title: 'Horlicks Biscuits',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/butter.png',
      title: '20 - 20 Butter Jeera Cookies',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/hideandseek.png',
      title: 'Hide & Seek Chocolate Chip',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
  ];

  static List<ProductModel> productListGlucoseBiscuits = [
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/horlicks.png',
      title: 'Horlicks Biscuits',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/butter.png',
      title: '20 - 20 Butter Jeera Cookies',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/sub_categories/biscuits/hideandseek.png',
      title: 'Hide & Seek Chocolate Chip',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
  ];

  static List<ProductModel> productListSeasonal = [
    const ProductModel(
      imgUrl: 'assets/images/home/carrots.png',
      title: 'Orange Carrot',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '0',
      inCartFlag: false,
    ),
    const ProductModel(
      imgUrl: 'assets/images/home/watermelon.png',
      title: 'Watermelon',
      weight: '6 pcs(Approx 1.2kg)',
      originalPrice: '199.45',
      discountedPrice: '99.45',
      offPercentage: '15',
      inCartFlag: true,
      inCartQuantity: 10,
    ),
  ];
}
